name: taskly
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^9.3.0+1
  dio: ^5.8.0+1
  dio_smart_retry: ^6.0.0
  duration: ^4.0.3
  flash: ^3.1.1
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage_x: ^10.2.2
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  form_builder_validators: ^11.0.0
  google_fonts: ^6.2.1
  hive_ce_flutter: ^2.1.0
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  multiple_result: ^5.1.0
  platform_info: ^5.0.0
  responsive_framework:
    git:
      url: https://github.com/Shreemanarjun/ResponsiveFramework.git
      ref: v1.4.0
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  talker_dio_logger: ^4.6.10
  talker_flutter: ^4.6.3
  talker_riverpod_logger: ^4.6.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  riverpod_lint: ^2.6.3
  riverpod_test: ^0.1.6
  slang_build_runner: ^4.4.2
  spot: ^0.17.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
